version: "3.7"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: poydevor_workersdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api_gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api_gateway
    ports:
      - "9000:9000"
    depends_on:
      - workers_service
    

  workers_service: 
    build:
      context: ./workers-service
      dockerfile: Dockerfile
    container_name: workers_service
    ports:
      - "8081:8081"
    depends_on:
      - postgres

volumes:
  postgres_data: {}