services:
  workers-service:
    host: workers_service
    port: 8081

  users-service:
    host: users_service
    port: 8082
    
  api-gateway:
    host: api_gateway
    port: 9000

tls:
  cert_file: ./tls/cert.pem
  key_file: ./tls/key.pem