// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package storage

import (
	"context"
)

const insertUser = `-- name: InsertUser :exec
INSERT INTO users
    (login, password)
VALUES 
    ($1, $2)
`

type InsertUserParams struct {
	Login    string
	Password string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser, arg.Login, arg.Password)
	return err
}

const login = `-- name: Login :one
SELECT id, login, password FROM users
WHERE login = $1
`

func (q *Queries) Login(ctx context.Context, login string) (User, error) {
	row := q.db.QueryRowContext(ctx, login, login)
	var i User
	err := row.Scan(&i.ID, &i.Login, &i.Password)
	return i, err
}
