// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package storage

import (
	"database/sql"
	"time"
)

type DailyProduction struct {
	ID          int32
	Date        time.Time
	CountBlocks int32
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullInt32
}

type DailyProductionWorker struct {
	ID                int32
	DailyProductionID int32
	WorkerID          int32
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
	DeletedAt         sql.NullInt32
}

type LoadProduction struct {
	ID          int32
	SendBlockID int32
	WorkerID    int32
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullInt32
}

type PaidMonthly struct {
	ID        int32
	Date      time.Time
	PaidPrice float64
	WorkerID  int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullInt32
}

type SendBlock struct {
	ID          int32
	Date        time.Time
	CountBlocks int32
	Address     string
	LoadPrice   int32
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullInt32
}

type Worker struct {
	ID        int32
	FirstName string
	LastName  string
	Phone     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullInt32
}
