CREATE TABLE IF NOT EXISTS paid_monthly (
    id SERIAL PRIMARY KEY,
    date DATE NOT NULL,
    paid_price FLOAT NOT NULL,
    worker_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at INT DEFAULT 0    
);