// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: protos/workers.proto

package workerspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Create Worker
type AddWorkersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddWorkersReq) Reset() {
	*x = AddWorkersReq{}
	mi := &file_protos_workers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWorkersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWorkersReq) ProtoMessage() {}

func (x *AddWorkersReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_workers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWorkersReq.ProtoReflect.Descriptor instead.
func (*AddWorkersReq) Descriptor() ([]byte, []int) {
	return file_protos_workers_proto_rawDescGZIP(), []int{0}
}

func (x *AddWorkersReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddWorkersReq) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *AddWorkersReq) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *AddWorkersReq) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type AddWorkersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddWorkersResp) Reset() {
	*x = AddWorkersResp{}
	mi := &file_protos_workers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWorkersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWorkersResp) ProtoMessage() {}

func (x *AddWorkersResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_workers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWorkersResp.ProtoReflect.Descriptor instead.
func (*AddWorkersResp) Descriptor() ([]byte, []int) {
	return file_protos_workers_proto_rawDescGZIP(), []int{1}
}

func (x *AddWorkersResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *AddWorkersResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Get Workers
type Worker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Worker) Reset() {
	*x = Worker{}
	mi := &file_protos_workers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Worker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Worker) ProtoMessage() {}

func (x *Worker) ProtoReflect() protoreflect.Message {
	mi := &file_protos_workers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Worker.ProtoReflect.Descriptor instead.
func (*Worker) Descriptor() ([]byte, []int) {
	return file_protos_workers_proto_rawDescGZIP(), []int{2}
}

func (x *Worker) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Worker) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Worker) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Worker) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type GetWorkersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkersReq) Reset() {
	*x = GetWorkersReq{}
	mi := &file_protos_workers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkersReq) ProtoMessage() {}

func (x *GetWorkersReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_workers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkersReq.ProtoReflect.Descriptor instead.
func (*GetWorkersReq) Descriptor() ([]byte, []int) {
	return file_protos_workers_proto_rawDescGZIP(), []int{3}
}

type GetWorkersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workers       []*Worker              `protobuf:"bytes,1,rep,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkersResp) Reset() {
	*x = GetWorkersResp{}
	mi := &file_protos_workers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkersResp) ProtoMessage() {}

func (x *GetWorkersResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_workers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkersResp.ProtoReflect.Descriptor instead.
func (*GetWorkersResp) Descriptor() ([]byte, []int) {
	return file_protos_workers_proto_rawDescGZIP(), []int{4}
}

func (x *GetWorkersResp) GetWorkers() []*Worker {
	if x != nil {
		return x.Workers
	}
	return nil
}

// EndDay
type EndDayReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	CountBlocks   int32                  `protobuf:"varint,3,opt,name=count_blocks,json=countBlocks,proto3" json:"count_blocks,omitempty"`
	Workers       []int32                `protobuf:"varint,4,rep,packed,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndDayReq) Reset() {
	*x = EndDayReq{}
	mi := &file_protos_workers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndDayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndDayReq) ProtoMessage() {}

func (x *EndDayReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_workers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndDayReq.ProtoReflect.Descriptor instead.
func (*EndDayReq) Descriptor() ([]byte, []int) {
	return file_protos_workers_proto_rawDescGZIP(), []int{5}
}

func (x *EndDayReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EndDayReq) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *EndDayReq) GetCountBlocks() int32 {
	if x != nil {
		return x.CountBlocks
	}
	return 0
}

func (x *EndDayReq) GetWorkers() []int32 {
	if x != nil {
		return x.Workers
	}
	return nil
}

type EndDayResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndDayResp) Reset() {
	*x = EndDayResp{}
	mi := &file_protos_workers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndDayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndDayResp) ProtoMessage() {}

func (x *EndDayResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_workers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndDayResp.ProtoReflect.Descriptor instead.
func (*EndDayResp) Descriptor() ([]byte, []int) {
	return file_protos_workers_proto_rawDescGZIP(), []int{6}
}

func (x *EndDayResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *EndDayResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// LoadBlocks
type LoadBlocksReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	CountBlocks   int64                  `protobuf:"varint,4,opt,name=count_blocks,json=countBlocks,proto3" json:"count_blocks,omitempty"`
	PriceBlock    int64                  `protobuf:"varint,5,opt,name=price_block,json=priceBlock,proto3" json:"price_block,omitempty"`
	Workers       []int32                `protobuf:"varint,6,rep,packed,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadBlocksReq) Reset() {
	*x = LoadBlocksReq{}
	mi := &file_protos_workers_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadBlocksReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadBlocksReq) ProtoMessage() {}

func (x *LoadBlocksReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_workers_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadBlocksReq.ProtoReflect.Descriptor instead.
func (*LoadBlocksReq) Descriptor() ([]byte, []int) {
	return file_protos_workers_proto_rawDescGZIP(), []int{7}
}

func (x *LoadBlocksReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LoadBlocksReq) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *LoadBlocksReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *LoadBlocksReq) GetCountBlocks() int64 {
	if x != nil {
		return x.CountBlocks
	}
	return 0
}

func (x *LoadBlocksReq) GetPriceBlock() int64 {
	if x != nil {
		return x.PriceBlock
	}
	return 0
}

func (x *LoadBlocksReq) GetWorkers() []int32 {
	if x != nil {
		return x.Workers
	}
	return nil
}

type LoadBlocksResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadBlocksResp) Reset() {
	*x = LoadBlocksResp{}
	mi := &file_protos_workers_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadBlocksResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadBlocksResp) ProtoMessage() {}

func (x *LoadBlocksResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_workers_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadBlocksResp.ProtoReflect.Descriptor instead.
func (*LoadBlocksResp) Descriptor() ([]byte, []int) {
	return file_protos_workers_proto_rawDescGZIP(), []int{8}
}

func (x *LoadBlocksResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *LoadBlocksResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// MonthlyReport
type MonthlyReportReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Month         string                 `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"`
	Year          string                 `protobuf:"bytes,3,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthlyReportReq) Reset() {
	*x = MonthlyReportReq{}
	mi := &file_protos_workers_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyReportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyReportReq) ProtoMessage() {}

func (x *MonthlyReportReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_workers_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyReportReq.ProtoReflect.Descriptor instead.
func (*MonthlyReportReq) Descriptor() ([]byte, []int) {
	return file_protos_workers_proto_rawDescGZIP(), []int{9}
}

func (x *MonthlyReportReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MonthlyReportReq) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *MonthlyReportReq) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

type EndDayData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	CountBlocks   int32                  `protobuf:"varint,2,opt,name=count_blocks,json=countBlocks,proto3" json:"count_blocks,omitempty"`
	WorkersCount  int32                  `protobuf:"varint,3,opt,name=workers_count,json=workersCount,proto3" json:"workers_count,omitempty"`
	WorkerShare   string                 `protobuf:"bytes,4,opt,name=worker_share,json=workerShare,proto3" json:"worker_share,omitempty"`
	TotalPrice    string                 `protobuf:"bytes,5,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndDayData) Reset() {
	*x = EndDayData{}
	mi := &file_protos_workers_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndDayData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndDayData) ProtoMessage() {}

func (x *EndDayData) ProtoReflect() protoreflect.Message {
	mi := &file_protos_workers_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndDayData.ProtoReflect.Descriptor instead.
func (*EndDayData) Descriptor() ([]byte, []int) {
	return file_protos_workers_proto_rawDescGZIP(), []int{10}
}

func (x *EndDayData) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *EndDayData) GetCountBlocks() int32 {
	if x != nil {
		return x.CountBlocks
	}
	return 0
}

func (x *EndDayData) GetWorkersCount() int32 {
	if x != nil {
		return x.WorkersCount
	}
	return 0
}

func (x *EndDayData) GetWorkerShare() string {
	if x != nil {
		return x.WorkerShare
	}
	return ""
}

func (x *EndDayData) GetTotalPrice() string {
	if x != nil {
		return x.TotalPrice
	}
	return ""
}

type LoadBlocksData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Date            string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	CountBlocks     int32                  `protobuf:"varint,2,opt,name=count_blocks,json=countBlocks,proto3" json:"count_blocks,omitempty"`
	WorkersCount    int32                  `protobuf:"varint,3,opt,name=workers_count,json=workersCount,proto3" json:"workers_count,omitempty"`
	BlocksPerWorker string                 `protobuf:"bytes,4,opt,name=blocks_per_worker,json=blocksPerWorker,proto3" json:"blocks_per_worker,omitempty"`
	TotalPrice      string                 `protobuf:"bytes,5,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LoadBlocksData) Reset() {
	*x = LoadBlocksData{}
	mi := &file_protos_workers_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadBlocksData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadBlocksData) ProtoMessage() {}

func (x *LoadBlocksData) ProtoReflect() protoreflect.Message {
	mi := &file_protos_workers_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadBlocksData.ProtoReflect.Descriptor instead.
func (*LoadBlocksData) Descriptor() ([]byte, []int) {
	return file_protos_workers_proto_rawDescGZIP(), []int{11}
}

func (x *LoadBlocksData) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *LoadBlocksData) GetCountBlocks() int32 {
	if x != nil {
		return x.CountBlocks
	}
	return 0
}

func (x *LoadBlocksData) GetWorkersCount() int32 {
	if x != nil {
		return x.WorkersCount
	}
	return 0
}

func (x *LoadBlocksData) GetBlocksPerWorker() string {
	if x != nil {
		return x.BlocksPerWorker
	}
	return ""
}

func (x *LoadBlocksData) GetTotalPrice() string {
	if x != nil {
		return x.TotalPrice
	}
	return ""
}

type PaidMonthly struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	PaidPrice     int64                  `protobuf:"varint,2,opt,name=paid_price,json=paidPrice,proto3" json:"paid_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaidMonthly) Reset() {
	*x = PaidMonthly{}
	mi := &file_protos_workers_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaidMonthly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaidMonthly) ProtoMessage() {}

func (x *PaidMonthly) ProtoReflect() protoreflect.Message {
	mi := &file_protos_workers_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaidMonthly.ProtoReflect.Descriptor instead.
func (*PaidMonthly) Descriptor() ([]byte, []int) {
	return file_protos_workers_proto_rawDescGZIP(), []int{12}
}

func (x *PaidMonthly) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *PaidMonthly) GetPaidPrice() int64 {
	if x != nil {
		return x.PaidPrice
	}
	return 0
}

type MonthlyReportResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// EndDayData
	EndDayData []*EndDayData `protobuf:"bytes,1,rep,name=end_day_data,json=endDayData,proto3" json:"end_day_data,omitempty"`
	// LoadBlocksData
	LoadBlocksData []*LoadBlocksData `protobuf:"bytes,2,rep,name=load_blocks_data,json=loadBlocksData,proto3" json:"load_blocks_data,omitempty"`
	// PaidMonthly
	PaidMonthly   []*PaidMonthly `protobuf:"bytes,3,rep,name=paid_monthly,json=paidMonthly,proto3" json:"paid_monthly,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthlyReportResp) Reset() {
	*x = MonthlyReportResp{}
	mi := &file_protos_workers_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyReportResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyReportResp) ProtoMessage() {}

func (x *MonthlyReportResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_workers_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyReportResp.ProtoReflect.Descriptor instead.
func (*MonthlyReportResp) Descriptor() ([]byte, []int) {
	return file_protos_workers_proto_rawDescGZIP(), []int{13}
}

func (x *MonthlyReportResp) GetEndDayData() []*EndDayData {
	if x != nil {
		return x.EndDayData
	}
	return nil
}

func (x *MonthlyReportResp) GetLoadBlocksData() []*LoadBlocksData {
	if x != nil {
		return x.LoadBlocksData
	}
	return nil
}

func (x *MonthlyReportResp) GetPaidMonthly() []*PaidMonthly {
	if x != nil {
		return x.PaidMonthly
	}
	return nil
}

// PaidWorkerMonthly
type PaidWorkerMonthlyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaidPrice     float32                `protobuf:"fixed32,1,opt,name=paid_price,json=paidPrice,proto3" json:"paid_price,omitempty"`
	WorkerId      int64                  `protobuf:"varint,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaidWorkerMonthlyReq) Reset() {
	*x = PaidWorkerMonthlyReq{}
	mi := &file_protos_workers_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaidWorkerMonthlyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaidWorkerMonthlyReq) ProtoMessage() {}

func (x *PaidWorkerMonthlyReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_workers_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaidWorkerMonthlyReq.ProtoReflect.Descriptor instead.
func (*PaidWorkerMonthlyReq) Descriptor() ([]byte, []int) {
	return file_protos_workers_proto_rawDescGZIP(), []int{14}
}

func (x *PaidWorkerMonthlyReq) GetPaidPrice() float32 {
	if x != nil {
		return x.PaidPrice
	}
	return 0
}

func (x *PaidWorkerMonthlyReq) GetWorkerId() int64 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

type PaidWorkerMonthlyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaidWorkerMonthlyResp) Reset() {
	*x = PaidWorkerMonthlyResp{}
	mi := &file_protos_workers_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaidWorkerMonthlyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaidWorkerMonthlyResp) ProtoMessage() {}

func (x *PaidWorkerMonthlyResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_workers_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaidWorkerMonthlyResp.ProtoReflect.Descriptor instead.
func (*PaidWorkerMonthlyResp) Descriptor() ([]byte, []int) {
	return file_protos_workers_proto_rawDescGZIP(), []int{15}
}

func (x *PaidWorkerMonthlyResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *PaidWorkerMonthlyResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_protos_workers_proto protoreflect.FileDescriptor

const file_protos_workers_proto_rawDesc = "" +
	"\n" +
	"\x14protos/workers.proto\"~\n" +
	"\rAddWorkersReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\"B\n" +
	"\x0eAddWorkersResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"w\n" +
	"\x06Worker\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\"\x0f\n" +
	"\rGetWorkersReq\"3\n" +
	"\x0eGetWorkersResp\x12!\n" +
	"\aworkers\x18\x01 \x03(\v2\a.WorkerR\aworkers\"l\n" +
	"\tEndDayReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12!\n" +
	"\fcount_blocks\x18\x03 \x01(\x05R\vcountBlocks\x12\x18\n" +
	"\aworkers\x18\x04 \x03(\x05R\aworkers\">\n" +
	"\n" +
	"EndDayResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xab\x01\n" +
	"\rLoadBlocksReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12!\n" +
	"\fcount_blocks\x18\x04 \x01(\x03R\vcountBlocks\x12\x1f\n" +
	"\vprice_block\x18\x05 \x01(\x03R\n" +
	"priceBlock\x12\x18\n" +
	"\aworkers\x18\x06 \x03(\x05R\aworkers\"B\n" +
	"\x0eLoadBlocksResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"L\n" +
	"\x10MonthlyReportReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05month\x18\x02 \x01(\tR\x05month\x12\x12\n" +
	"\x04year\x18\x03 \x01(\tR\x04year\"\xac\x01\n" +
	"\n" +
	"EndDayData\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12!\n" +
	"\fcount_blocks\x18\x02 \x01(\x05R\vcountBlocks\x12#\n" +
	"\rworkers_count\x18\x03 \x01(\x05R\fworkersCount\x12!\n" +
	"\fworker_share\x18\x04 \x01(\tR\vworkerShare\x12\x1f\n" +
	"\vtotal_price\x18\x05 \x01(\tR\n" +
	"totalPrice\"\xb9\x01\n" +
	"\x0eLoadBlocksData\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12!\n" +
	"\fcount_blocks\x18\x02 \x01(\x05R\vcountBlocks\x12#\n" +
	"\rworkers_count\x18\x03 \x01(\x05R\fworkersCount\x12*\n" +
	"\x11blocks_per_worker\x18\x04 \x01(\tR\x0fblocksPerWorker\x12\x1f\n" +
	"\vtotal_price\x18\x05 \x01(\tR\n" +
	"totalPrice\"@\n" +
	"\vPaidMonthly\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"paid_price\x18\x02 \x01(\x03R\tpaidPrice\"\xae\x01\n" +
	"\x11MonthlyReportResp\x12-\n" +
	"\fend_day_data\x18\x01 \x03(\v2\v.EndDayDataR\n" +
	"endDayData\x129\n" +
	"\x10load_blocks_data\x18\x02 \x03(\v2\x0f.LoadBlocksDataR\x0eloadBlocksData\x12/\n" +
	"\fpaid_monthly\x18\x03 \x03(\v2\f.PaidMonthlyR\vpaidMonthly\"R\n" +
	"\x14PaidWorkerMonthlyReq\x12\x1d\n" +
	"\n" +
	"paid_price\x18\x01 \x01(\x02R\tpaidPrice\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\x03R\bworkerId\"I\n" +
	"\x15PaidWorkerMonthlyResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb9\x02\n" +
	"\x0eWorkersService\x12-\n" +
	"\n" +
	"AddWorkers\x12\x0e.AddWorkersReq\x1a\x0f.AddWorkersResp\x12-\n" +
	"\n" +
	"GetWorkers\x12\x0e.GetWorkersReq\x1a\x0f.GetWorkersResp\x12!\n" +
	"\x06EndDay\x12\n" +
	".EndDayReq\x1a\v.EndDayResp\x12-\n" +
	"\n" +
	"LoadBlocks\x12\x0e.LoadBlocksReq\x1a\x0f.LoadBlocksResp\x126\n" +
	"\rMonthlyReport\x12\x11.MonthlyReportReq\x1a\x12.MonthlyReportResp\x12?\n" +
	"\x0eAddPaidMonthly\x12\x15.PaidWorkerMonthlyReq\x1a\x16.PaidWorkerMonthlyRespB\x14Z\x12genproto/workerspbb\x06proto3"

var (
	file_protos_workers_proto_rawDescOnce sync.Once
	file_protos_workers_proto_rawDescData []byte
)

func file_protos_workers_proto_rawDescGZIP() []byte {
	file_protos_workers_proto_rawDescOnce.Do(func() {
		file_protos_workers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_workers_proto_rawDesc), len(file_protos_workers_proto_rawDesc)))
	})
	return file_protos_workers_proto_rawDescData
}

var file_protos_workers_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_protos_workers_proto_goTypes = []any{
	(*AddWorkersReq)(nil),         // 0: AddWorkersReq
	(*AddWorkersResp)(nil),        // 1: AddWorkersResp
	(*Worker)(nil),                // 2: Worker
	(*GetWorkersReq)(nil),         // 3: GetWorkersReq
	(*GetWorkersResp)(nil),        // 4: GetWorkersResp
	(*EndDayReq)(nil),             // 5: EndDayReq
	(*EndDayResp)(nil),            // 6: EndDayResp
	(*LoadBlocksReq)(nil),         // 7: LoadBlocksReq
	(*LoadBlocksResp)(nil),        // 8: LoadBlocksResp
	(*MonthlyReportReq)(nil),      // 9: MonthlyReportReq
	(*EndDayData)(nil),            // 10: EndDayData
	(*LoadBlocksData)(nil),        // 11: LoadBlocksData
	(*PaidMonthly)(nil),           // 12: PaidMonthly
	(*MonthlyReportResp)(nil),     // 13: MonthlyReportResp
	(*PaidWorkerMonthlyReq)(nil),  // 14: PaidWorkerMonthlyReq
	(*PaidWorkerMonthlyResp)(nil), // 15: PaidWorkerMonthlyResp
}
var file_protos_workers_proto_depIdxs = []int32{
	2,  // 0: GetWorkersResp.workers:type_name -> Worker
	10, // 1: MonthlyReportResp.end_day_data:type_name -> EndDayData
	11, // 2: MonthlyReportResp.load_blocks_data:type_name -> LoadBlocksData
	12, // 3: MonthlyReportResp.paid_monthly:type_name -> PaidMonthly
	0,  // 4: WorkersService.AddWorkers:input_type -> AddWorkersReq
	3,  // 5: WorkersService.GetWorkers:input_type -> GetWorkersReq
	5,  // 6: WorkersService.EndDay:input_type -> EndDayReq
	7,  // 7: WorkersService.LoadBlocks:input_type -> LoadBlocksReq
	9,  // 8: WorkersService.MonthlyReport:input_type -> MonthlyReportReq
	14, // 9: WorkersService.AddPaidMonthly:input_type -> PaidWorkerMonthlyReq
	1,  // 10: WorkersService.AddWorkers:output_type -> AddWorkersResp
	4,  // 11: WorkersService.GetWorkers:output_type -> GetWorkersResp
	6,  // 12: WorkersService.EndDay:output_type -> EndDayResp
	8,  // 13: WorkersService.LoadBlocks:output_type -> LoadBlocksResp
	13, // 14: WorkersService.MonthlyReport:output_type -> MonthlyReportResp
	15, // 15: WorkersService.AddPaidMonthly:output_type -> PaidWorkerMonthlyResp
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_protos_workers_proto_init() }
func file_protos_workers_proto_init() {
	if File_protos_workers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_workers_proto_rawDesc), len(file_protos_workers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_workers_proto_goTypes,
		DependencyIndexes: file_protos_workers_proto_depIdxs,
		MessageInfos:      file_protos_workers_proto_msgTypes,
	}.Build()
	File_protos_workers_proto = out.File
	file_protos_workers_proto_goTypes = nil
	file_protos_workers_proto_depIdxs = nil
}
